"""Markdown trade report for tracking execution and P&L."""

from __future__ import annotations

import logging
import re
from datetime import datetime, timezone
from decimal import Decimal
from pathlib import Path
from typing import List, Optional

logger = logging.getLogger(__name__)

_FILE_HEADER = (
    "# Trade Report\n"
    "\n"
    "> Auto-generated by the Delta-Neutral Funding Arb Bot.  \n"
    "> Each section is one trading day (UTC). Most recent day first.\n"
)


def _fmt(value: Optional[Decimal], decimals: int = 6) -> str:
    if value is None:
        return "\u2014"
    return f"{value:.{decimals}f}"


def _today_tag() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d")


def _timestamp() -> str:
    return datetime.now(timezone.utc).strftime("%H:%M:%S")


# ---------------------------------------------------------------------------
# Section-based file manipulation
# ---------------------------------------------------------------------------

class _DaySection:
    """One day's worth of entries + its computed summary."""

    def __init__(self, date_tag: str, entries: List[str]) -> None:
        self.date_tag = date_tag
        self.entries = entries  # raw trade lines (no summary, no heading)

    def render(self) -> str:
        summary = self._build_summary()
        entry_block = "\n".join(self.entries)
        return f"## {self.date_tag}\n\n{summary}\n### Trades\n\n{entry_block}\n"

    def _build_summary(self) -> str:
        opens = 0
        closes = 0
        total_open_notional = Decimal("0")
        total_close_notional = Decimal("0")
        symbols = set()

        for line in self.entries:
            notional = self._extract_decimal(line, r"Notional:\s*\$([\d,]+\.?\d*)")
            symbol = self._extract_text(line, r"\*\*(?:OPEN|CLOSE)\s+(\S+)\*\*")
            if symbol:
                symbols.add(symbol)

            if "**OPEN" in line:
                opens += 1
                if notional:
                    total_open_notional += notional
            elif "**CLOSE" in line:
                closes += 1
                if notional:
                    total_close_notional += notional

        rebalances = closes // 2

        return (
            "| Metric | Value |\n"
            "|--------|-------|\n"
            f"| Trades | {opens} opens, {closes} closes |\n"
            f"| Rebalances | ~{rebalances} |\n"
            f"| Symbols | {', '.join(sorted(symbols)) or '\u2014'} |\n"
            f"| Open notional | ${total_open_notional:,.2f} |\n"
            f"| Close notional | ${total_close_notional:,.2f} |\n"
        )

    @staticmethod
    def _extract_decimal(text: str, pattern: str) -> Optional[Decimal]:
        m = re.search(pattern, text)
        if m:
            try:
                return Decimal(m.group(1).replace(",", ""))
            except Exception:
                return None
        return None

    @staticmethod
    def _extract_text(text: str, pattern: str) -> Optional[str]:
        m = re.search(pattern, text)
        return m.group(1) if m else None


def _parse_file(path: Path) -> List[_DaySection]:
    """Parse an existing report into day sections."""
    if not path.exists():
        return []

    text = path.read_text(encoding="utf-8")
    sections: List[_DaySection] = []

    # Split on day headings: ## YYYY-MM-DD
    parts = re.split(r"(?=^## \d{4}-\d{2}-\d{2})", text, flags=re.MULTILINE)

    for part in parts:
        m = re.match(r"^## (\d{4}-\d{2}-\d{2})", part)
        if not m:
            continue
        date_tag = m.group(1)

        # Extract only the trade entry lines (starting with "- `")
        entries = [line for line in part.splitlines() if line.startswith("- `") or line.startswith("  ")]

        # Re-group: each entry starts with "- `", continuation lines start with "  "
        grouped: List[str] = []
        for line in entries:
            if line.startswith("- `"):
                grouped.append(line)
            elif grouped:
                grouped[-1] += "\n" + line

        sections.append(_DaySection(date_tag, grouped))

    return sections


def _write_report(path: Path, sections: List[_DaySection]) -> None:
    """Write the full report from sections, most recent first."""
    path.parent.mkdir(parents=True, exist_ok=True)
    sections.sort(key=lambda s: s.date_tag, reverse=True)
    body = "\n\n".join(s.render() for s in sections)
    path.write_text(f"{_FILE_HEADER}\n{body}\n", encoding="utf-8")


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def log_trade(
    path: Path,
    *,
    action: str,
    symbol: str,
    side: str,
    venue: str,
    quantity: Decimal,
    price: Decimal,
    leverage: int = 1,
    funding_rate: Optional[Decimal] = None,
    funding_apy: Optional[Decimal] = None,
    apy_difference: Optional[Decimal] = None,
    estimated_fee_bps: Optional[Decimal] = None,
    notes: str = "",
) -> None:
    """Append a trade entry to the markdown report and update the daily summary."""
    notional = quantity * price
    ts = _timestamp()
    today = _today_tag()

    # Build the entry as a single string (first line + indented continuation)
    parts = [f"- `{ts}` **{action} {symbol}** {side} on **{venue}**"]
    parts.append(f"  Qty: {_fmt(quantity)} | Price: ${_fmt(price, 2)} | Notional: ${notional:,.2f}")
    if leverage > 1:
        parts.append(f"  Leverage: {leverage}x")

    detail_bits: List[str] = []
    if funding_rate is not None:
        detail_bits.append(f"Rate: {_fmt(funding_rate, 8)}")
    if apy_difference is not None:
        detail_bits.append(f"APY diff: {_fmt(apy_difference, 2)}%")
    if estimated_fee_bps is not None:
        detail_bits.append(f"Est. fee: {_fmt(estimated_fee_bps, 1)} bps")
    if notes:
        detail_bits.append(notes)
    if detail_bits:
        parts.append(f"  {' | '.join(detail_bits)}")

    entry = "\n".join(parts)

    try:
        sections = _parse_file(path)

        # Find or create today's section
        today_section = next((s for s in sections if s.date_tag == today), None)
        if today_section is None:
            today_section = _DaySection(today, [])
            sections.append(today_section)

        today_section.entries.append(entry)
        _write_report(path, sections)
    except OSError as exc:
        logger.error("Failed to write trade log: %s", exc)
